package com.whzxw.uface.ether.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.whzxw.uface.ether.database.PersonTable;

import com.whzxw.uface.ether.database.PersonTableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personTableDaoConfig;

    private final PersonTableDao personTableDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personTableDaoConfig = daoConfigMap.get(PersonTableDao.class).clone();
        personTableDaoConfig.initIdentityScope(type);

        personTableDao = new PersonTableDao(personTableDaoConfig, this);

        registerDao(PersonTable.class, personTableDao);
    }
    
    public void clear() {
        personTableDaoConfig.clearIdentityScope();
    }

    public PersonTableDao getPersonTableDao() {
        return personTableDao;
    }

}
